name: Test
on:
    push:
        branches:
            - master
    pull_request:

jobs:
    test:
        name: Test
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v1
            - name: Install
              run: yarn install --frozen-lockfile
            - name: Spell Check
              run: yarn check-spelling
            - name: Test
              run: yarn test-ci
            - name: Build
              run: yarn build
